CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_profile_personal_create`(
	accountid int,
    first_name varchar(45),
    last_name varchar(45),
    middle_name varchar(45),
    prefix varchar(45),
    suffix varchar(45),
    gender int,
    birth_date date,
	phone_mobile varchar(15),
    phone_home varchar(15),
    phone_emergency varchar(15),
    email_id varchar(45),
    marital_status int, 
	religion int, 
	nationality int, 
	caste int, 
	height_inches int, 
	height_cms int,
	weight int, 
	weight_units varchar(4), 
	complexion int, 
	linkedin varchar(450), 
	facebook varchar(450), 
	instagram varchar(450), 
	whatsapp_number varchar(15), 
	profession int, 
	disability int,
	created_user varchar(45)
)
BEGIN
	If exists(select * from account where account_id = accountid ) Then
		Insert into profile_personal (
		account_id ,
		first_name ,
		last_name ,
		middle_name ,
		prefix ,
		suffix ,
		gender ,
		birth_date ,
		phone_mobile,
		phone_home ,
		phone_emergency ,
		email_id,
		marital_status , 
		religion , 
		nationality , 
		caste , 
		height_inches , 
		height_cms ,
		weight , 
		weight_units , 
		complexion , 
		linkedin , 
		facebook , 
		instagram , 
		whatsapp_number , 
		profession , 
		disability ,
		is_active , 
		created_date , 
		created_user 
		) 
		values(
		accountid ,
		first_name ,
		last_name ,
		middle_name ,
		prefix ,
		suffix ,
		gender ,
		birth_date ,
		phone_mobile,
		phone_home ,
		phone_emergency ,
		email_id,
		marital_status , 
		religion , 
		nationality , 
		caste , 
		height_inches , 
		height_cms ,
		weight , 
		weight_units , 
		complexion , 
		linkedin , 
		facebook , 
		instagram , 
		whatsapp_number , 
		profession , 
		disability ,
		1 , 
		now() , 
		created_user
	);
		
		select last_insert_id() as last;
	else
		select 'Invalid Account ID';
	End if;

END