CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_profile_family_refernce_create`(
	profileid int, 
	reference_type int, 
	first_name varchar(45), 
	last_name varchar(45), 
	middle_name varchar(45), 
	alias varchar(45), 
	gender int, 
	date_of_birth date, 
	religion int, 
	nationality int, 
	caste int, 
	marital_status int, 
	highest_education int, 
	disability int,
	address_line1 varchar(50), 
	city varchar(45), 
	state varchar(45), 
	country varchar(45), 
	zip varchar(45), 
	primary_phone varchar(45), 
	secondary_phone varchar(45), 
	can_communicate tinyint, 
	email varchar(45), 
	linkedin varchar(45), 
	instagram varchar(45), 
	facebook varchar(45), 
	whatsapp varchar(45), 
	employment_status varchar(45),
	emp_company_name varchar(45), 
	emp_city varchar(45), 
	emp_state varchar(45), 
	emp_country varchar(45), 
	emp_zip varchar(45),
    account_id int
)
BEGIN
	IF EXISTS(SELECT * FROM profile_personal WHERE profile_id = profileid) THEN
		INSERT INTO profile_family_reference (
			profile_id, 
			reference_type, 
			first_name, 
			last_name, 
			middle_name, 
			alias, 
			gender, 
			date_of_birth, 
			religion, 
			nationality, 
			caste, 
			marital_status, 
			highest_education, 
			disability,
			address_line1, 
			city, 
			state, 
			country, 
			zip, 
			primary_phone, 
			secondary_phone, 
			can_communicate, 
			email, 
			linkedin, 
			instagram, 
			facebook, 
			whatsapp, 
			employment_status,
			emp_company_name, 
			emp_city, 
			emp_state, 
			emp_country, 
			emp_zip,
			date_created,
			user_created
        )
        VALUES (
			profileid, 
			reference_type, 
			first_name, 
			last_name, 
			middle_name, 
			alias, 
			gender, 
			date_of_birth, 
			religion, 
			nationality, 
			caste, 
			marital_status, 
			highest_education, 
			disability,
			address_line1, 
			city, 
			state, 
			country, 
			zip, 
			primary_phone, 
			secondary_phone, 
			can_communicate, 
			email, 
			linkedin, 
			instagram, 
			facebook, 
			whatsapp, 
			employment_status,
			emp_company_name, 
			emp_city, 
			emp_state, 
			emp_country, 
			emp_zip,
			now(),
			account_id
        );
	ELSE
		SELECT 'Profile doesnot exist';
	END IF;
END