CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `uvw_get_profile_info` AS
    SELECT DISTINCT
        `person`.`profile_id` AS `profile_id`,
        `person`.`account_id` AS `account_id`,
        `person`.`first_name` AS `first_name`,
        `person`.`last_name` AS `last_name`,
        `person`.`middle_name` AS `middle_name`,
        `person`.`prefix` AS `prefix`,
        `person`.`suffix` AS `suffix`,
        `person`.`gender` AS `gender`,
        `person`.`birth_date` AS `birth_date`,
        `person`.`phone_mobile` AS `phone_mobile`,
        `person`.`phone_home` AS `phone_home`,
        `person`.`phone_emergency` AS `phone_emergency`,
        `person`.`email_id` AS `email_id`,
        `person`.`marital_status` AS `marital_status`,
        `person`.`religion` AS `religion`,
        `person`.`nationality` AS `nationality`,
        `person`.`caste` AS `caste`,
        `person`.`height_inches` AS `height_inches`,
        `person`.`height_cms` AS `height_cms`,
        `person`.`weight` AS `weight`,
        `person`.`weight_units` AS `weight_units`,
        `person`.`complexion` AS `complexion`,
        `person`.`linkedin` AS `linkedin`,
        `person`.`facebook` AS `facebook`,
        `person`.`instagram` AS `instagram`,
        `person`.`whatsapp_number` AS `whatsapp_number`,
        `person`.`profession` AS `profession`,
        `person`.`disability` AS `disability`,
        `person`.`is_active` AS `is_active`,
        `person`.`activated_date` AS `activated_date`,
        `address`.`address_type` AS `address_type`,
        `address`.`address_line1` AS `address_line1`,
        `address`.`address_line2` AS `address_line2`,
        `address`.`city` AS `city`,
        `address`.`state` AS `state`,
        `address`.`country` AS `country`,
        `address`.`zip` AS `zip`,
        `address`.`phone` AS `phone`,
        `address`.`landmark1` AS `landmark1`,
        `address`.`landmark2` AS `landmark2`,
        `bgv`.`verification_type` AS `verification_type`,
        `bgv`.`status` AS `bgv_status`,
        `bgv`.`start_date` AS `bgv_start_date`,
        `bgv`.`completed_date` AS `bgv_completed_date`,
        `bgv`.`verificaiton_notes` AS `bgv_verificaiton_notes`,
        `bgv`.`admin_remarks` AS `bgv_admin_remarks`,
        `bgv`.`fee_paid` AS `bgv_fee_paid`,
        `bgv`.`verification_completed_by` AS `verification_completed_by`,
        `bgv`.`is_document_available` AS `is_document_available`,
        `bgv`.`document_location` AS `document_location`,
        `bgv_approval`.`is_signed` AS `is_signed`,
        `bgv_approval`.`signed_doc_location` AS `signed_doc_location`,
        `bgv_approval`.`fee_agreed` AS `fee_agreed`,
        `complexion`.`name` AS `complexion_name`,
        `complexion`.`description` AS `complexion_description`,
        `complexion`.`status` AS `Complexion_status`,
        `education`.`education_level` AS `education_level`,
        `education`.`year_completed` AS `year_completed`,
        `education`.`institution_name` AS `institution_name`,
        `education`.`address_line1` AS `education_address_line1`,
        `education`.`city` AS `education_city`,
        `education`.`state` AS `education_state`,
        `education`.`country` AS `education_country`,
        `education`.`zip` AS `education_zip`,
        `education`.`field_of_study` AS `field_of_study`,
        `employment`.`institution_name` AS `employment_institution_name`,
        `employment`.`address_line1` AS `employment_address_line1`,
        `employment`.`city` AS `employment_city`,
        `employment`.`state` AS `employment_state`,
        `employment`.`country` AS `employment_country`,
        `employment`.`zip` AS `employment_zip`,
        `employment`.`start_year` AS `employment_start_year`,
        `employment`.`end_year` AS `employment_end_year`,
        `employment`.`job_title` AS `job_title`,
        `employment`.`last_salary_drawn` AS `last_salary_drawn`,
        `property`.`property_type` AS `property_type`,
        `property`.`ownership_type` AS `ownership_type`,
        `property`.`address_line1` AS `property_address_line1`,
        `property`.`city` AS `property_city`,
        `property`.`state` AS `property_state`,
        `property`.`country` AS `property_country`,
        `property`.`zip` AS `property_zip`,
        `property`.`landmark1` AS `property_landmark1`,
        `property`.`landmark2` AS `property_landmark2`,
        `reference`.`reference_type` AS `reference_type`,
        `reference`.`first_name` AS `reference_first_name`,
        `reference`.`last_name` AS `reference_last_name`,
        `reference`.`middle_name` AS `reference_middle_name`,
        `reference`.`alias` AS `reference_alias`,
        `reference`.`gender` AS `reference_gender`,
        `reference`.`date_of_birth` AS `reference_date_of_birth`,
        `reference`.`religion` AS `reference_religion`,
        `reference`.`nationality` AS `reference_nationality`,
        `reference`.`caste` AS `reference_caste`,
        `reference`.`marital_status` AS `reference_marital_status`,
        `reference`.`highest_education` AS `reference_highest_education`,
        `reference`.`disability` AS `reference_disability`,
        `reference`.`address_line1` AS `reference_address_line1`,
        `reference`.`city` AS `reference_city`,
        `reference`.`state` AS `reference_state`,
        `reference`.`country` AS `reference_country`,
        `reference`.`zip` AS `reference_zip`,
        `reference`.`primary_phone` AS `reference_primary_phone`,
        `reference`.`secondary_phone` AS `reference_secondary_phone`,
        `reference`.`can_communicate` AS `reference_can_communicate`,
        `reference`.`email` AS `reference_email`,
        `reference`.`linkedin` AS `reference_linkedin`,
        `reference`.`instagram` AS `reference_instagram`,
        `reference`.`facebook` AS `reference_facebook`,
        `reference`.`whatsapp` AS `reference_whatsapp`,
        `reference`.`employment_status` AS `reference_employment_status`,
        `reference`.`emp_company_name` AS `reference_emp_company_name`,
        `reference`.`emp_city` AS `reference_emp_city`,
        `reference`.`emp_state` AS `reference_emp_state`,
        `reference`.`emp_country` AS `reference_emp_country`,
        `reference`.`emp_zip` AS `reference_emp_zip`,
        `hobby`.`hobby_id` AS `hobby_id`,
        `hobby`.`description` AS `hobby_description`,
        `interest`.`interest_id` AS `interest_id`,
        `interest`.`description` AS `interest_description`,
        `partner`.`partner_id` AS `partner_id`,
        `partner`.`share_with_others` AS `partner_share_with_others`,
        `partner`.`document_location` AS `partner_document_location`,
        `photo`.`type` AS `photo_type`,
        `photo`.`description` AS `photo_description`,
        `photo`.`caption` AS `photo_caption`,
        `photo`.`url` AS `photo_url`
    FROM
        (((((((((((((`profile_personal` `person`
        JOIN `profile_address` `address` ON ((`address`.`profile_id` = `person`.`profile_id`)))
        JOIN `profile_bgv` `bgv` ON ((`bgv`.`profile_id` = `person`.`profile_id`)))
        JOIN `profile_bgv_approval` `bgv_approval` ON ((`bgv_approval`.`profile_id` = `person`.`profile_id`)))
        JOIN `profile_complexion` `complexion` ON ((`complexion`.`id` = `person`.`profile_id`)))
        JOIN `profile_education` `education` ON ((`education`.`profile_id` = `person`.`profile_id`)))
        JOIN `profile_employment` `employment` ON ((`employment`.`profile_id` = `person`.`profile_id`)))
        JOIN `profile_family_property` `property` ON ((`property`.`profile_id` = `person`.`profile_id`)))
        JOIN `profile_family_reference` `reference` ON ((`reference`.`profile_id` = `person`.`profile_id`)))
        JOIN `profile_hobby` `hobby` ON ((`hobby`.`profile_id` = `person`.`profile_id`)))
        JOIN `profile_interest` `interest` ON ((`interest`.`profile_id` = `person`.`profile_id`)))
        JOIN `profile_partner` `partner` ON ((`partner`.`profile_id` = `person`.`profile_id`)))
        JOIN `profile_personal` `personal` ON ((`personal`.`profile_id` = `person`.`profile_id`)))
        JOIN `profile_photo` `photo` ON ((`photo`.`profile_id` = `person`.`profile_id`)))