CREATE TABLE `profile_personal` (
  `profile_id` int NOT NULL AUTO_INCREMENT,
  `account_id` int NOT NULL,
  `first_name` varchar(45) NOT NULL,
  `last_name` varchar(45) NOT NULL,
  `middle_name` varchar(45) DEFAULT NULL,
  `prefix` varchar(45) DEFAULT NULL,
  `suffix` varchar(45) DEFAULT NULL,
  `gender` int NOT NULL,
  `birth_date` date NOT NULL,
  `phone_mobile` varchar(15) NOT NULL COMMENT 'mobile phone with country code',
  `phone_home` varchar(15) DEFAULT NULL,
  `phone_emergency` varchar(15) DEFAULT NULL,
  `email_id` varchar(45) NOT NULL,
  `marital_status` int NOT NULL,
  `religion` int DEFAULT NULL,
  `nationality` int DEFAULT NULL,
  `caste` int DEFAULT NULL,
  `height_inches` int DEFAULT NULL,
  `height_cms` int DEFAULT NULL,
  `weight` int DEFAULT NULL,
  `weight_units` varchar(4) DEFAULT NULL COMMENT 'LB OR KG',
  `complexion` int DEFAULT NULL,
  `linkedin` varchar(450) DEFAULT NULL,
  `facebook` varchar(450) DEFAULT NULL,
  `instagram` varchar(450) DEFAULT NULL,
  `whatsapp_number` varchar(15) DEFAULT NULL,
  `profession` int DEFAULT NULL,
  `disability` int DEFAULT NULL,
  `is_active` tinyint DEFAULT NULL,
  `activated_date` datetime DEFAULT NULL,
  `user_activated` varchar(45) DEFAULT NULL,
  `deactivation_date` datetime DEFAULT NULL,
  `user_deactivated` varchar(45) DEFAULT NULL,
  `deactivation_reason` varchar(450) DEFAULT NULL,
  `is_deleted` tinyint DEFAULT NULL,
  `deleted_date` datetime DEFAULT NULL,
  `user_deleted` varchar(45) DEFAULT NULL,
  `deleted_reason` varchar(450) DEFAULT NULL,
  `is_full_bgv_verified` tinyint DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `created_user` varchar(45) DEFAULT NULL,
  `modified_date` datetime DEFAULT NULL,
  `modified_user` varchar(45) DEFAULT NULL,
  `profile_personalcol` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`profile_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci