-- Insert values for professions with definitions
INSERT INTO lkp_profession(name, description)
VALUES
    ('Accountant', 'A professional responsible for financial record-keeping, analysis, and reporting.'),
    ('Actor/Actress', 'An individual who performs on stage, in films, or on television.'),
    ('Architect', 'A professional involved in the planning, design, and oversight of building structures.'),
    ('Artist', 'A person skilled in one of the fine arts, such as painting, sculpture, or music.'),
    ('Attorney/Lawyer', 'A legal professional providing advice, representation, and advocacy in legal matters.'),
    ('Baker', 'A person who bakes and sells bread, cakes, and pastries.'),
    ('Barista', 'A person who prepares and serves coffee, often in a coffee shop.'),
    ('Biologist', 'A scientist specializing in the study of living organisms and their interactions.'),
    ('Chef', 'A professional cook skilled in the preparation of food.'),
    ('Civil Engineer', 'An engineer involved in the planning and design of civil infrastructure projects.'),
    ('Content Creator', 'An individual who produces and publishes digital content, often on social media platforms.'),
    ('Data Scientist', 'A professional who analyzes and interprets complex data sets to inform business decisions.'),
    ('Dentist', 'A medical professional specializing in the treatment of oral health issues.'),
    ('Doctor/Physician', 'A medical professional qualified to practice medicine, diagnose illnesses, and prescribe treatments.'),
    ('Electrician', 'A skilled tradesperson who installs, repairs, and maintains electrical systems.'),
    ('Engineer', 'A professional trained in various branches of engineering.'),
    ('Fashion Designer', 'A professional who designs clothing and accessories.'),
    ('Financial Analyst', 'A professional who analyzes financial data to provide insights and recommendations.'),
    ('Graphic Designer', 'A professional who creates visual content for print and digital media.'),
    ('Hair Stylist', 'A professional trained in cutting, coloring, and styling hair.'),
    ('IT Professional', 'A professional working in the field of information technology.'),
    ('Journalist', 'A person who gathers, writes, and reports news for media outlets.'),
    ('Marketing Specialist', 'A professional specializing in promoting and selling products or services.'),
    ('Musician', 'A person skilled in playing a musical instrument or singing.'),
    ('Nurse', 'A healthcare professional providing care and support to patients.'),
    ('Nutritionist', 'A professional specializing in the study of nutrition and dietary practices.'),
    ('Paramedic', 'A healthcare professional trained to provide emergency medical care.'),
    ('Pharmacist', 'A healthcare professional responsible for dispensing medications and providing advice on their use.'),
    ('Photographer', 'A person who captures and creates images using a camera.'),
    ('Pilot', 'A person trained to operate an aircraft.'),
    ('Police Officer', 'A law enforcement professional responsible for maintaining public safety and enforcing laws.'),
    ('Professor/Teacher', 'An educator who imparts knowledge and skills to students.'),
    ('Psychologist', 'A professional trained in the study of the human mind and behavior.'),
    ('Real Estate Agent', 'A professional involved in the buying and selling of real estate.'),
    ('Research Scientist', 'A scientist engaged in research and experimentation.'),
    ('Sales Representative', 'A professional responsible for selling products or services.'),
    ('Social Worker', 'A professional providing support and services to individuals and communities.'),
    ('Software Developer', 'A professional involved in the design and creation of computer software.'),
    ('Speech Therapist', 'A healthcare professional specializing in speech and language therapy.'),
    ('Surgeon', 'A medical professional trained to perform surgical procedures.'),
    ('Surveyor', 'A professional responsible for measuring and mapping land.'),
    ('Taxi Driver', 'A person who drives a taxi to transport passengers.'),
    ('Teacher', 'An educator who imparts knowledge and skills to students.'),
    ('Technician', 'A skilled worker who specializes in a particular field or industry.'),
    ('Translator', 'A professional who translates written or spoken content from one language to another.'),
    ('Travel Agent', 'A professional who assists individuals in planning and booking travel.'),
    ('Truck Driver', 'A person who drives trucks to transport goods.'),
    ('Veterinarian', 'A medical professional specializing in the health and care of animals.'),
    ('Waiter/Waitress', 'A person who serves food and beverages to customers in a restaurant.'),
    ('Web Developer', 'A professional involved in the design and development of websites.');
