-- Insert values for community/caste with definitions
INSERT INTO lkp_caste(name, description)
VALUES
    ('Brahmin', 'A member of the highest Hindu caste, traditionally a priest or scholar.'),
    ('Kshatriya', 'A member of the second-highest Hindu caste, traditionally warriors and rulers.'),
    ('Vaishya', 'A member of the third-highest Hindu caste, traditionally merchants and landowners.'),
    ('Shudra', 'A member of the fourth and lowest Hindu caste, traditionally servants and laborers.'),
    ('Agarwal', 'A community associated with business and trade in the Indian subcontinent.'),
    ('Ahir', 'A community traditionally associated with cattle-herding and farming.'),
    ('Arora', 'A Punjabi community engaged in trade and commerce.'),
    ('Balija/Goud', 'A community found in Southern India, traditionally engaged in agriculture and business.'),
    ('Bania', 'A merchant community engaged in trade and commerce.'),
    ('Bunt', 'A community found in coastal Karnataka, India, engaged in agriculture and business.'),
    ('Chettiar', 'A mercantile and business community in Tamil Nadu, India.'),
    ('Chettiar', 'Another community with the same name, traditionally engaged in trade and commerce.'),
    ('Devar', 'A community found in Southern India, engaged in various occupations including agriculture.'),
    ('Garhwali', 'An ethnic group from the Garhwal region of the Indian state of Uttarakhand.'),
    ('Goundar', 'A community traditionally associated with agriculture and trade.'),
    ('Gounder', 'Another community with a similar name, traditionally engaged in agriculture and business.'),
    ('Gujjar', 'A pastoral and agricultural community found in India and Pakistan.'),
    ('Gupta', 'A community historically associated with administrative and business roles.'),
    ('Iyengar', 'A subsect of the Brahmin community, primarily based in Southern India.'),
    ('Iyer', 'Another subsect of the Brahmin community, primarily based in Southern India.'),
    ('Jat', 'A community traditionally associated with agriculture and military service.'),
    ('Jat Sikh', 'A Sikh sub-group of the Jat community, known for their agricultural background.'),
    ('Kalar', 'A community traditionally engaged in various occupations including agriculture.'),
    ('Kamma', 'A community found in Southern India, traditionally engaged in agriculture and trade.'),
    ('Kamma Naidu', 'A subsect of the Kamma community with a similar background.'),
    ('Kapu', 'A community found in Southern India, engaged in agriculture and business.'),
    ('Kapu Naidu', 'A subsect of the Kapu community with a similar background.'),
    ('Kayastha', 'A community historically associated with administrative and literary roles.'),
    ('Khandelwal', 'A business community known for trade and commerce.'),
    ('Khatri', 'A Punjabi trading community traditionally engaged in business.'),
    ('Khokhar', 'A community found in Northern India, traditionally engaged in agriculture.'),
    ('Kori', 'A community engaged in various occupations including agriculture and trade.'),
    ('Kumaoni', 'An ethnic group from the Kumaon region of the Indian state of Uttarakhand.'),
    ('Labana', 'A Sikh trading and farming community.'),
    ('Lingayat', 'A community in Southern India with a distinct religious identity.'),
    ('Maheshwari', 'A business community known for trade and commerce.'),
    ('Maratha', 'A martial community from the western Indian state of Maharashtra.'),
    ('Mazhabi', 'A Sikh community historically associated with the military.'),
    ('Meena', 'An indigenous community found in Rajasthan, India.'),
    ('Menon', 'A Kerala-based community with diverse occupations.'),
    ('Mudaliar', 'A Tamil-speaking community engaged in trade and commerce.'),
    ('Mudaliar', 'Another community with the same name, traditionally engaged in trade and commerce.'),
    ('Nadar', 'A community found in Southern India, engaged in various occupations including business.'),
    ('Naidu', 'A title used by various communities in Southern India, indicating social standing.'),
    ('Nair', 'A community from the Indian state of Kerala, historically associated with various roles.'),
    ('Parsi', 'A Zoroastrian community that migrated to India from Persia.'),
    ('Patel', 'A title used by various agricultural and business communities in India.'),
    ('Pillai', 'A Tamil-speaking community historically engaged in trade and administration.'),
    ('Rajput', 'A martial community historically associated with ruling princely states.'),
    ('Ramgharia', 'A Sikh community known for carpentry, blacksmithing, and related trades.'),
    ('Ravidasia', 'A Sikh community historically associated with leatherwork.'),
    ('Reddy', 'A community found in Southern India, traditionally engaged in agriculture and business.'),
    ('Sindhi', 'An ethnic group with a diverse range of occupations, historically associated with Sindh.'),
    ('Teli', 'A business community traditionally associated with oil pressing and trade.'),
    ('Thakur', 'A title used by various communities, often indicating a landowning or warrior status.'),
    ('Valmiki', 'A community historically associated with the occupation of sweeping and sanitation.'),
    ('Vanniyar', 'A community found in Southern India, traditionally engaged in agriculture and trade.'),
    ('Velama', 'A community found in Southern India, traditionally engaged in agriculture and trade.'),
    ('Vokkaliga', 'A community found in Southern India, traditionally engaged in agriculture.'),
    ('Yadav', 'A community traditionally associated with agriculture and animal husbandry.');
